name: Release
on:
  push:
    branches: [master, next]

jobs:
  semantic-release:
    name: Bump version and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branches: |
            [
              'master',
              { name: 'next', prerelease: true }
            ]
          extra_plugins: |
            @semantic-release/git
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
